### ISSUE TITLE
Allow for annotations for volumesnapshotclasses via values file

### ISSUE THREAD

**Issue by linedpaper** [democratic-csi/charts#15]
My apologies if I am just not understanding how well enough to accomplish this, but it seems any annotations I add to my values.yaml are ignored and I don't see annotations in snapshot-classes.yaml, would it be possible to add?  I need annotations for Kasten K10 to allow snapshots.  I have manually added this for now, but I assume if I upgrade I will need to manually add again.

    k10.kasten.io/is-snapshot-class: "true"

**Comment by travisghansen** [comment]
Seems easy enough. It would be awesome if you could write a blog entry about the setup/integration and share with us! I’m interested to know how it works.

I’ll try to get it in there in the next day or so otherwise PRs welcome.

**Comment by linedpaper** [comment]
I’m pretty new to this myself, but there wasn’t anything to it other than adding that annotation.  Kasten has a helm chart and unless you feed it a value it will just use the default storage class.  Aside from that I setup my jobs, retention and s3 exports in the web dashboard it provides, but the annotation was all that was needed to allow snapshots on TrueNas, well and the crd’s and snapshot setup already mentioned on the Readme.

**Comment by travisghansen** [comment]
Yeah, I’m interested in knowing what it does behind the scenes to actually access the data stored in the snapshots. Does it create a temporary pvc/pod and then push the data to the destination? I’m intrigued..

**Comment by travisghansen** [comment]
Looking at it more closely it doesn’t actually do any backup/snapshots itself but rather automates/orchestrates the creation of snapshots in the k8s api etc?

**Comment by linedpaper** [comment]
Yes, that's correct, it only orchestrates it all, allows me to make easy schedules for snapshots, will sync to S3 storage, etc.  It's actually owned by Veeam as of end of 2020 I think.

**Comment by travisghansen** [comment]
Does it sync snapshot content to s3? Or only k8s resource definitions?

**Comment by travisghansen** [comment]
Yeah interesting...so you can make it send the actual content of a snapshot to an s3 endpoint? I'm interesting to know how that works specifically. I wonder it takes a snapshot, then relies on the pvc from snapshot functionality to create a new pvc, etc. Mostly just curious how it's implemented.

**Comment by travisghansen** [comment]
support added here https://github.com/democratic-csi/charts/commit/96ff56fc0859e779a97427a64dd54f4f10e936b2 and released in chart `v0.8.0`. Try it out and let me know how it goes.

**Comment by linedpaper** [comment]
Confirmed working for me.  I removed the annotation from the volumesnapshotclasses prior to upgrading and it was back after upgrading using my values.yaml.  Thanks so much for the quick add!

**Comment by linedpaper** [comment]
And I am sorry I can't speak more to exactly how Kasten is doing what it does for exports as I am brand new to it.
