### ISSUE TITLE
Compatibility issues with K8s 1.22

### ISSUE THREAD

**Issue by solidDoWant** [democratic-csi/charts#18]
[Kubernetes 1.22 is removing apiextensions.k8s.io/v1beta support](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/). As a result, the custom resource definition needs to be updated. I was able to get it working by slightly modifying it as shown here, but I don't know enough about CRDs to tell if I did it properly or not. If [this](https://github.com/solidDoWant/infra-mk2/blob/main/cluster/crds/democratic-csi/crds.yaml) works (with some slight changes for Helm) and you want to upgrade the version  I can open a PR.

**Comment by travisghansen** [comment]
The crd isn’t required since version 1.14 of k8s so you probably shouldn’t be installing it anyway. But I can add per version logic easily enough.

**Comment by solidDoWant** [comment]
Oh really? Thank you! I'll remove it from my cluster.
