### ISSUE TITLE
Helm install dryrun

### ISSUE THREAD

**Issue by Shifter2600** [democratic-csi/charts#2]
I get this error after I
helm install freenas democratic-csi/democratic-csi --dry-run

Error: execution error at (democratic-csi/templates/required.yaml:1:5): csiDriver.name is required

I suspect I need to pass in some values but I am unsure how to add these in.

**Comment by Shifter2600** [comment]
Ahh I think I understand now. I need to pass in a yaml I create with my settings.
helm install freenas democratic-csi/democratic-csi -f myvalues.yaml
and use your freenas-nfs.yaml as a template.

**Comment by travisghansen** [comment]
Yes that's correct. Did it go ok so far?

**Comment by Shifter2600** [comment]
Hitting an error on the deploy. The 5/5 controllers and running
but the nodes are 2/3 and showing a CrashloopBackoff  and RunContainerErrors

RunContainerError: failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/a557d452fa4267b548cfd6b1127dab1a59f5e1043f6447be549ca04b45fd404a/rootfs\\\" at \\\"/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/a557d452fa4267b548cfd6b1127dab1a59f5e1043f6447be549ca04b45fd404a/rootfs/usr/share/zoneinfo/UCT\\\" caused \\\"not a directory\\\"\"": unknown

**Comment by travisghansen** [comment]
Pretty common to set that up..what distro are you running?

Should look something like this..

```
ls -l /etc/localtime
lrwxrwxrwx. 1 root root 36 May 31  2018 /etc/localtime -> ../usr/share/zoneinfo/America/Denver
``

**Comment by Shifter2600** [comment]
k3os and k3s.
ls -l /etc/localtime
total 0

**Comment by travisghansen** [comment]
Interesting, k3os is quite minimal. Not sure if you can use cloud-init to set that value or not. Is the fs immutable or can you manually set the link?

**Comment by Shifter2600** [comment]
Looks like there was some merges in april with someone with a similar need. Ya looks like I can set it in the config.yaml by writing a file. Just means I need to rebuild my cluster here not a big deal but i'll need to get to that tomorrow. Thx for the help. I will report back once I have the localtime set in there.
https://github.com/rancher/k3os/issues/103

**Comment by travisghansen** [comment]
Ah ok cool. Thanks for trying it out. I'll get around to putting proper documentation in place as well.

What version of k8s are you running?

When I last did the charts I built them with the alpha support for snapshots which has since gone beta (and changed relatively substantially) so the chart isn't really equipped to deal with snapshot classes etc as is. In other words, leave those blank for now.

**Comment by Shifter2600** [comment]
k3s from rancher labs.
Looks like it is going to be a straight forward addition to the config.yaml
sudo ln -vs /usr/share/zoneinfo/America/Edmonton /etc/localtime 
that will populate it.

**Comment by travisghansen** [comment]
What’s the current version of k8s being installed by it? Is it 1.18?

**Comment by Shifter2600** [comment]
Ya 1.18..
That didn't work same error.
RunContainerError: failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/2982f3eeeb5758b328efa78e71b5c0598152389693360b98bb24c30267278b15/rootfs\\\" at \\\"/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/2982f3eeeb5758b328efa78e71b5c0598152389693360b98bb24c30267278b15/rootfs/usr/share/zoneinfo/UCT\\\" caused \\\"not a directory\\\"\"": unknown

**Comment by travisghansen** [comment]
Hmm. I’ll setup a cluster with k3os and give it a whirl. In the mean time localtime is probably not critical and can likely be removed from the DaemonSet manually if you’re comfortable doing that kind of thing.

**Comment by Shifter2600** [comment]
I'd rather figure out how to get k3s compliant since it will likely come up again with other deploys. I have some messages out on their slack to see what to do about the time. I wonder if it's the symlink its having an issue with?

**Comment by travisghansen** [comment]
I was wondering about that myself. It seems like something funny with some sort of overlay fs or whatever that’s making it kinda weird. Can you copy the file in place instead of the symlink?

**Comment by Shifter2600** [comment]
Here is the structure. /etc looks like it gets wiped on reboot so I'll have to find a way to get that file in there on build and on boot I guess
/etc - ephemeral 
/usr - read-only (except /usr/local is writable and persistent) 
/k3os - system files 
/home - persistent 
/var - persistent 
/opt - persistent 
/usr/local - persistent

**Comment by travisghansen** [comment]
Yeah OK. I'm not quite ready to fire up a cluster with k3os but slowly working through my weekend list and I'll get there. I do quite a bit of stuff with rancher's products so I don't imagine it will be too much of a learning curve but if you want to shout out any configs/build steps you're doing to fast track it that would be good.

I added that mount to the chart simply because it's pretty common among the other csi installations (NetApp trident, openebs, etc) so yeah, you'll probably want a solid solution for this to fully solve the issue.

**Comment by Shifter2600** [comment]
configMACADDRESS.yaml
`ssh_authorized_keys:
- ssh-rsa ....
- ssh-rsa ....
hostname: k3sMACADDRESS

k3os:
  dns_nameservers:
  - 8.8.8.8
  - 1.1.1.1
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  token: g......n
  labels:
    cores: 8
  k3s_args:
  - server
  - "--tls-san" 
  - "k3s.domain.com"
  - "--advertise-address" 
  - "192.168.0.1"
  - "--bind-address" 
  - "192.168.0.1"
  environment:
    K3S_DATASTORE_ENDPOINT: mysql://admin:pass@tcp(192.168.0.10:3306)/k3s
    TZ: America/Edmonton
`
I just added the TZ to environment based on another user. I will go ahead and rebuild my cluster here. BTW I use PXE with this script which brings in this config.
`#!ipxe

imgfree
kernel https://github.com/rancher/k3os/releases/download/v0.10.1/k3os-vmlinuz-amd64 console=tty1 console=serial loglevel=4 k3os.debug printk.devkmsg=on k3os.mode=install k3os.install.silent k3os.install.device=/dev/sda k3os.install.iso_url=https://github.com/rancher/k3os/releases/download/v0.10.1/k3os-amd64.iso k3os.install.config_url=https://git.listy.ai/root/k3os/-/raw/master/configMACADDRESS.yaml k3os.install.power_off=false
initrd https://github.com/rancher/k3os/releases/download/v0.10.1/k3os-initrd-amd64
imgstat
boot`

**Comment by Shifter2600** [comment]
I got it 👍 with help from this post https://github.com/rancher/k3os/issues/103
https://pastebin.com/2fCnqwPu
base64 /usr/share/zoneinfo/America/Edmonton
take the output and remove the linefeeds into one line and replace the content with your timezone.

**Comment by Shifter2600** [comment]
Just rolled it on one node so far and the container fully deployed. Now just need to roll though the other 5 and PXE boot with the new config addition.

**Comment by travisghansen** [comment]
Nice! Let me know how provisioning goes. Not sure if k3os includes all the necessary nfs/iscsi packages by default? I'd also recommend setting up iscsi as well.

For me I have 2 deployments of democratic-csi one for nfs and the other for iscsi. If you have all the right stuff in place on the nodes (iscsiadm, nfs-utils, etc) then you should have a pretty decent setup to roll with for however many clusters (run each cluster/deployment with it's own parent dataset).

You will inevitably find workloads that are just better with iscisi. nfs is nice and easy to start with but iscsi is really the better option unless you really need multiple nodes/pods to access the same storage. If you want/need help getting iscsi configured on the server let me know.

**Comment by Shifter2600** [comment]
Success so far I have both deployed and now need to try setting up some PVC's

**Comment by travisghansen** [comment]
Very cool. Keep me updated.

Does k3os come with all the necessary host-level requirements for iscsi to work?

**Comment by Shifter2600** [comment]
Yes and it's all working so the only hang up was really the localtime timezone thing which is all in my config.yaml when the nodes get built

**Comment by travisghansen** [comment]
Cool! Keep me updated and let me know if you run into anything weird. I’ll get the snapshot support cleaned up and then that should be in good enough shape to start using again as well.
