### ISSUE TITLE
CRDs are too old and do not work on 1.20+ clusters

### ISSUE THREAD

**Issue by djbobyd** [democratic-csi/charts#24]
Hi Travis,
I just wanted to let you know that the CRDs that are referenced in the values. yaml  file are too old and do not work with newer clusters.
The link https://raw.githubusercontent.com/kubernetes/csi-api/master/pkg/crd/manifests/csidriver.yaml points to a 3 years old file and trying to enable CRD installation through helm returns the following error:

`Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): missing required field "versions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]`

Not a big deal as everything is working without this. However I guess it could be a problem for new installations.

Best Regards,
Borislav

**Comment by travisghansen** [comment]
Thanks! That crd should be removed from the chart at this point. It was only required for clusters < 1.14 so it’s useless on anything even remotely modern.

**Comment by djbobyd** [comment]
Great, 
You can use this issue then to track the removal or you could open another one. I just wanted to help, so I don't care if this stays open :)

**Comment by travisghansen** [comment]
Yeah we can leave this open. The short is you should not be trying to install the crd with the chart...it's built-in now to k8s and should not be modified manually.
