### ISSUE TITLE
Resource limits

### ISSUE THREAD

**Issue by deefdragon** [democratic-csi/charts#25]
I am currently on V 1.5.4 due to [this issue](https://github.com/democratic-csi/democratic-csi/issues/164), and I am seeing the iscsi controller specifically slowly increasing memory used over time. Currently some are over 3.5GB of memory (nearly 25% of the node memory). I would like to limit the memory (and other resources) used by the image if possible.

**Comment by travisghansen** [comment]
I had a bug in a version of the proxy image, which version of that is currently deployed?

**Comment by deefdragon** [comment]
I upped it to 0.4.2 today (some had hit 7Gb and actually brought cluster workers down, so it became a must fix.), though looking through the resources, it looks like both csi-proxy and csi-driver were rather heavy on the memory usage, 40-60.

**Comment by deefdragon** [comment]
@travisghansen is the addition of resource limits still just on your local branch?

**Comment by travisghansen** [comment]
added in `v0.13.1`.

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/charts/commit/f58f097e94f3c0fd5ef15d4758d6c61b14c9bcea
