### ISSUE TITLE
K3OS NFS test pod failed with error

### ISSUE THREAD

**Issue by Shifter2600** [democratic-csi/charts#3]
The Claim was successful and created the datasets
https://pastebin.com/3mz5hs9x
There was a small issue though it didn't like claims under 1Gi freenas error on the dataset created "Quota size is too small, enter a value of 1 GiB or larger."

Then I deployed the Pod
https://pastebin.com/m3GCGt1N
kubectl describe pod freenas-test-pod

Normal   Scheduled    <unknown>            default-scheduler         Successfully assigned default/freenas-test-pod to k3s3497f6566641
  Warning  FailedMount  114s                 kubelet, k3s3497f6566641  Unable to attach or mount volumes: unmounted volumes=[freenas-test-volume], unattached volumes=[freenas-test-volume default-token-x5t2j]: timed out waiting for the condition
  Warning  FailedMount  18s (x9 over 3m47s)  kubelet, k3s3497f6566641  MountVolume.MountDevice failed for volume "pvc-0490758b-a3b4-460d-9cc6-b9ab4521dc6a" : rpc error: code = Internal desc = [object Object]

**Comment by Shifter2600** [comment]
FYI I got the iscsi working it creates and deletes as expected.

**Comment by travisghansen** [comment]
Hmm that’s a helpful error message. Can you manually mount one of the shares from a node?

**Comment by travisghansen** [comment]
That is what I was looking for yes. Do you see the share/dataset in FreeNAS as appropriate?

**Comment by Shifter2600** [comment]
Ya the share is there and I just did another test with the old NFS and it is still working. iscsi is still working as well so it's just the CSI NFS that is not operational. I am trying some compares on the shares that got created using the old way vs the CSI way. Trying to diagnose

**Comment by Shifter2600** [comment]
I adjusted the settings in the CSI NFS to match the exact setup for the share options that work in the older NFS setup and I still get the error.
Normal   Scheduled    <unknown>         default-scheduler         Successfully assigned default/freenas-test-pod to k3s3497f6566641
  Warning  FailedMount  6s (x2 over 17s)  kubelet, k3s3497f6566641  MountVolume.MountDevice failed for volume "pvc-8b91f7be-fa72-46be-8462-1cae4a9f4554" : rpc error: code = Internal desc = [object Object]
I changed 
```yaml
zfs:
      datasetEnableReservation: true
```
and
```yaml
nfs:
      shareAlldirs: true
```
Because the one from the old way came in with those set. 
Could it be something in the pod not set properly I just took the pod from the old NFS one and edited it to use the CSI NFS PVC
https://pastebin.com/hWYNeCcr

**Comment by travisghansen** [comment]
I need to make that error code saner and actually turn the object into string so we know what’s up. You can set the `node.driver.logLevel` to `debug` and then get the logs from the corresponding container/pod on the node trying to start the pod using the share...that may give is a clue where it’s failing.

**Comment by travisghansen** [comment]
I mean get the logs from the csi driver container on the node that’s trying to mount the nfs share. It may be enough with just info level but setting debug will certainly give us more insight.

**Comment by Shifter2600** [comment]
Got it. This should help point you in the right direction of where it is erroring.
error: handler error - driver: FreeNASDriver method: NodeStageVolume error: {"code":32,"stdout":"","stderr":"mount.nfs: rpc.statd is not running but is required for remote locking.\nmount.nfs: Either use '-o nolock' to keep locks local, or start statd.\n"}
{ code: 13, message: '[object Object]' }
info: new request - driver: FreeNASDriver method: NodeGetCapabilities call: {"_events":{},"_eventsCount":1,"call":{},"cancelled":false,"metadata":{"_internal_repr":{"user-agent":["grpc-go/1.25.1"]},"flags":0},"request":{}}
info: new response - driver: FreeNASDriver method: NodeGetCapabilities response: {"capabilities":[{"rpc":{"type":"STAGE_UNSTAGE_VOLUME"}},{"rpc":{"type":"GET_VOLUME_STATS"}}]}
info: new request - driver: FreeNASDriver method: NodeStageVolume call: {"_events":{},"_eventsCount":1,"call":{},"cancelled":false,"metadata":{"_internal_repr":{"user-agent":["grpc-go/1.25.1"]},"flags":0},"request":{"publish_context":{},"secrets":"redacted","volume_context":{"share":"/mnt/tank/k8s/a/vols/pvc-8b91f7be-fa72-46be-8462-1cae4a9f4554","storage.kubernetes.io/csiProvisionerIdentity":"1590531274761-8081-org.democratic-csi.nfs","node_attach_driver":"nfs","provisioner_driver":"freenas-nfs","server":"192.168.210.12"},"volume_id":"pvc-8b91f7be-fa72-46be-8462-1cae4a9f4554","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8b91f7be-fa72-46be-8462-1cae4a9f4554/globalmount","volume_capability":{"access_mode":{"mode":"MULTI_NODE_MULTI_WRITER"},"mount":{"mount_flags":["noatime","nfsvers=3"],"fs_type":"nfs"},"access_type":"mount"}}}
executing fileystem command: stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8b91f7be-fa72-46be-8462-1cae4a9f4554/globalmount
executing mount command: findmnt --source 192.168.210.12:/mnt/tank/k8s/a/vols/pvc-8b91f7be-fa72-46be-8462-1cae4a9f4554 --mountpoint /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8b91f7be-fa72-46be-8462-1cae4a9f4554/globalmount --output source,target,fstype,label,options,avail,size,used -b -J
executing mount command: mount -t nfs -o noatime,nfsvers=3,defaults 192.168.210.12:/mnt/tank/k8s/a/vols/pvc-8b91f7be-fa72-46be-8462-1cae4a9f4554 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8b91f7be-fa72-46be-8462-1cae4a9f4554/globalmount

**Comment by travisghansen** [comment]
Can you send over the mount options of the successful mount with the other provisioner? It’s certainly locking but seems odd that the other doesn’t have the same requirements...

This is easy to solve but I’d like to see that first.

**Comment by Shifter2600** [comment]
the other pvc that works has no mount options and the new CSI one has 
Mount Options
noatime
nfsvers=3

**Comment by Shifter2600** [comment]
I removed the mount options in the new CSI yaml and now it works. Do you want to look into it further and find out why the mount options made it fail. I can help diagnose more.

**Comment by travisghansen** [comment]
Can you run the mount command on the node and send over the output for the relevant mounts?

**Comment by Shifter2600** [comment]
I don't follow, do you mean run the CSI NFS with each of the mount options?
Mount Options
noatime
and
Mount Options
nfsvers=3

**Comment by travisghansen** [comment]
No, just go to the/a node that has a pod using the share and run `mount | grep nfs` and send over the output (or relevant output from the shares in question).

**Comment by Shifter2600** [comment]
mount | grep nfs
tmpfs on /var/lib/kubelet/pods/7a812936-b4dd-48ad-844e-41eda4ac9140/volumes/kubernetes.io~secret/freenfs-democratic-csi-node-sa-token-rdbcp type tmpfs (rw,relatime)
This is the share as it sits now working.

**Comment by travisghansen** [comment]
That's actually noise. It just so happens to have `nfs` in the `freenfs` path but isn't actually an `nfs` mount.

I want those details from the share(s) that are working however..

**Comment by Shifter2600** [comment]
I'll have to create a new pod because this pod doesn't continue to run it just runs and writes the file and stops. I'll get your the details ASAP.

**Comment by Shifter2600** [comment]
192.168.210.12:/mnt/tank/k8s/a/vols/pvc-f075cb9c-6344-492b-893e-879bbdde3d5d on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f075cb9c-6344-492b-893e-879bbdde3d5d/globalmount type nfs4 (rw,relatime,vers=4.1,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.210.113,local_lock=none,addr=192.168.210.12)
192.168.210.12:/mnt/tank/k8s/a/vols/pvc-f075cb9c-6344-492b-893e-879bbdde3d5d on /var/lib/kubelet/pods/e6e54153-dcb6-41f2-a5bb-66c75c891eac/volumes/kubernetes.io~csi/pvc-f075cb9c-6344-492b-893e-879bbdde3d5d/mount type nfs4 (rw,relatime,vers=4.1,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.210.113,local_lock=none,addr=192.168.210.12)

**Comment by travisghansen** [comment]
Thanks!

Yeah, that's the trouble..it's defaulting to nfs version 4. Unless you *really* have a specific use-case for nfsv4 I'd recommend against it (I am not however, an expert on the matter). Which means getting the rpc.statd running on your nodes or adding the `nolock` options to the storage class(es).

```
  mountOptions:
  - noatime
  - nfsvers=3
  - nolock
```

I think it can be quite dangerous to not have file locking though so I'd be digging into enabling the service on your os.

Depending on your use-case(s) I'd also revert the other changes you made regarding reservation and all dirs if appropriate...they have no impact on this error you're hitting at all.

**Comment by Shifter2600** [comment]
here is that output with those options.
192.168.210.12:/mnt/tank/k8s/a/vols/pvc-a346e907-acbb-438b-9261-ed43b7d82fa6 on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-a346e907-acbb-438b-9261-ed43b7d82fa6/globalmount type nfs (rw,noatime,vers=3,rsize=131072,wsize=131072,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.210.12,mountvers=3,mountport=975,mountproto=udp,local_lock=all,addr=192.168.210.12)
192.168.210.12:/mnt/tank/k8s/a/vols/pvc-a346e907-acbb-438b-9261-ed43b7d82fa6 on /var/lib/kubelet/pods/3893030e-ab95-46fe-87fb-0341c8d80942/volumes/kubernetes.io~csi/pvc-a346e907-acbb-438b-9261-ed43b7d82fa6/mount type nfs (rw,noatime,vers=3,rsize=131072,wsize=131072,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.210.12,mountvers=3,mountport=975,mountproto=udp,local_lock=all,addr=192.168.210.12)

**Comment by travisghansen** [comment]
Yeah, any luck getting the service to run so you don’t have to use nolock?

**Comment by Shifter2600** [comment]
I have a comment on the slack. Nfs-common doesnt exist and either does a package installer on k3os.

**Comment by travisghansen** [comment]
Cool. Interested in what you find out..

So the nodes do have the iscsi tools installed and the daemon running by default?

**Comment by Shifter2600** [comment]
Yes iscsiadm and iscsid are running.  Here is what I just found NFS is not running so I ran sudo service nfs start and now I can use the 
mountOptions:
  - noatime
  - nfsvers=3
I'll have to add that cmd to the boot in my config.yaml so it starts everytime.
192.168.210.12:/mnt/tank/k8s/a/vols/pvc-f54d2d1c-68cf-4f4f-af7f-a8d59edb18f1 on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f54d2d1c-68cf-4f4f-af7f-a8d59edb18f1/globalmount type nfs (rw,noatime,vers=3,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.210.12,mountvers=3,mountport=975,mountproto=udp,local_lock=none,addr=192.168.210.12)
192.168.210.12:/mnt/tank/k8s/a/vols/pvc-f54d2d1c-68cf-4f4f-af7f-a8d59edb18f1 on /var/lib/kubelet/pods/7e727c64-e8d2-4e19-817f-956de9ec5618/volumes/kubernetes.io~csi/pvc-f54d2d1c-68cf-4f4f-af7f-a8d59edb18f1/mount type nfs (rw,noatime,vers=3,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.210.12,mountvers=3,mountport=975,mountproto=udp,local_lock=none,addr=192.168.210.12)
You mentioned I needed to get file lock enabled 
What mount option is that?

**Comment by travisghansen** [comment]
File locking is implicitly enabled if you don't set the `nolock` option. So if it's mounting with the above setup you should be on your way! You may of course hone those options in more as needed/desired.

Congrats! The k8s people are working on making the supporting apps/images cross platform. When that happens I'll update everything to use versions that support all that fun stuff (the provisioner itself is already cross platform) and simultaneously fix up the snapshot stuff to work with the beta apis (or maybe they'll be GA by then which would be great).

**Comment by Shifter2600** [comment]
here is what I was able to add to the config.yaml to get NFS starting on boot.
```yaml
run_cmd:
  - "service rpcbind start"
  - "service nfs start"
```

**Comment by travisghansen** [comment]
I like it. Lets add k3os to the bug title so if anyone else finds this they’ll have some indicators of what they may do :)

**Comment by Shifter2600** [comment]
Ya add the localtime requirements as well.
`run_cmd:
  - "service rpcbind start"
  - "service nfs start"`
https://pastebin.com/2fCnqwPu
base64 /usr/share/zoneinfo/America/Edmonton
take the output and remove the linefeeds into one line and replace the content with your timezone.

**Comment by Shifter2600** [comment]
I posted in the K3OS slack as well so you might get some traffic from that too.
