### ISSUE TITLE
Breaking changes: CustomResourceDefinition & field is immutable

### ISSUE THREAD

**Issue by maxirus** [democratic-csi/charts#30]
### Overview

Releases `v0.12.0` and (potentially) `v0.13.1` are breaking releases. If following SemVer, these should have been `v1.0.0` and `v2.0.0` respectively. Typically a CHANGELOG would exist with Upgrade notes.

Ideally, to resolve this issue, a `CHANGELOG.md` should exist that clearly shows changes made and potential breaking changes, along with special upgrade notes.

### Upgrading to `v0.12.0`:

This is the same issue as #28 but wanted to add more details. When upgrading to `v0.12.0`, you'll likely face the following errors:

```bash
Error: cannot patch "<release-name>-democratic-csi-node" with kind DaemonSet: DaemonSet.apps "<release-name>-democratic-csi-node" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"node-linux", "app.kubernetes.io/csi-role":"node", "app.kubernetes.io/instance":"<release-name>", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"democratic-csi"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && cannot patch "<release-name>-democratic-csi-controller" with kind Deployment: Deployment.apps "<release-name>-democratic-csi-controller" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"controller-linux", "app.kubernetes.io/csi-role":"controller", "app.kubernetes.io/instance":"<release-name>", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"democratic-csi"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**and**

```bash
Error: cannot patch "<release-name>-democratic-csi-controller" with kind Deployment: Deployment.apps "<release-name>-democratic-csi-controller" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"controller-linux", "app.kubernetes.io/csi-role":"controller", "app.kubernetes.io/instance":"<release-name>", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"democratic-csi"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

To resolve, you need to delete the DaemonSet and Deployment for the respective pods. To do this, run:

```bash
kubectl delete deployment --namespace <your_namespace> <release-name>-democratic-csi-controller
```

```bash
kubectl delete ds --namespace <your_namespace> <release-name>-democratic-csi-node
```

Now you should be able to successfully run your helm upgrade command.

### Upgrading to v0.13.1

This one isn't exactly the fault of the Helm chart but more so K8s. In `v0.13.1`, the CRD was removed (issue #18 & #24) due to its incompatibility with K8s >v1.21. But CRDs are not automatically removed (or updated) and manual intervention is required. As such, you may run into the following error:

```bash
Error: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

The easiest way to resolve this issue is by using the [Helm MapKubeAPIs](https://github.com/helm/helm-mapkubeapis) plugin.

```bash
helm mapkubeapis --namespace <your_namespace> <release-name>
```

### Conclusion

I hope this helps other folks that ran into these issues and notes like above end-up documented somewhere (CHANGELOG, README, etc.)

**Comment by travisghansen** [comment]
Yeah thanks for the notes. A note on the crd (that should also be documented along with info shared above) is that effectively the crd should have never been used as it has been included in k8s for a long time 1.14+ (which effectively predates this project and nearly predates csi in k8s).

If using a gitops tool (like argocd) measures should be taken to **not** remove the crd from the cluster.
