### ISSUE TITLE
Ability to set pods priority

### ISSUE THREAD

**Issue by plyul** [democratic-csi/charts#35]
AFAIK, currently there is no possibility to set democratic-csi's pods priority (priorityClass).
Pods are running with default priority class so they can be preempted/evicted, which seems like a bad idea.

It would be nice to have some options to set deployed pods priority. Anoter option is to hardcode some high priority class like `system-node-critical` for example.

**Comment by travisghansen** [comment]
Closed by the above. Thanks for the suggestion!
