### ISSUE TITLE
lustre support from helm chart

### ISSUE THREAD

**Issue by dtwork2022** [democratic-csi/charts#37]
Is lustre not supported from helm chart? I don't see an example listed for it.

**Comment by travisghansen** [comment]
Yeah good question. It's effectively the same as this: https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/examples/nfs-client.yaml

The values file and comments look more complex than it actually is.

**Comment by travisghansen** [comment]
Just added this: https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/examples/lustre-client.yaml

Note that the lustre driver has not had a lot of usage so any feedback is helpful. Particularly the mount/node aspect may have some rough edges :(
