### ISSUE TITLE
Question regarding dataset creation

### ISSUE THREAD

**Issue by lzhengqc** [democratic-csi/charts#4]
Two questions:
1) Do we need enable ssh access for this to work?

2) Do we need to create an existing dataset or it can create a new dataset under the pool automatically. 

Thanks

**Comment by travisghansen** [comment]
Thanks for the interest!

1. It was designed to do a majority of actions over ssh for primarily 3 reasons
 - avoid the rough FreeNAS api (inconsistencies between versions, bugs, etc)
 - Get powerful features that aren’t available via the api
 - make the logic as agnostic as possible (it actually is the exact same code paths to run on zfs on linux for example using ubuntu or whatever

2. Parent datasets will be automatically created for you

You are welcome to use a password or ssh key. I’m not a ssh guru but I believe you may be able to limit based in key the commands that can be executed. I don’t have a full audit of them ATM but its pretty limited (zfs, zpool, chmod, chown)
