### ISSUE TITLE
Should this run on arm64 please?

### ISSUE THREAD

**Issue by PBXForums** [democratic-csi/charts#5]
I have a cluster of Pi4s that I am trying to implement this on.

I just get crash loop backoff for all the pods.

The logs seem to indicate a problem with driver registrar container and maybe the cleanup container. I'm very, very new to all of this so I'm unsure.

kubectl logs democratic-csi-1591404995-node-w2tsd csi-driver
info: initializing csi driver: freenas-iscsi
info: starting csi server - name: org.democratic-csi.iscsi, version: 0.1.0, driver: freenas-iscsi, mode: node, csi version: 1.1.0, address: , socket: unix:///csi-data/csi.sock

kubectl logs democratic-csi-1591404995-node-w2tsd driver-registrar
standard_init_linux.go:211: exec user process caused "exec format error"

 kubectl logs democratic-csi-1591404995-node-w2tsd cleanup
standard_init_linux.go:211: exec user process caused "exec format error"

TIA
Daz

**Comment by travisghansen** [comment]
My code should be multi-arch however there are numerous other bits revolving around csi (all the ‘sidecar’ containers) that are not. There has been some movement recently though on several so I’m (as well as all other csi drivers) optimistic we’ll have them before long.

**Comment by PBXForums** [comment]
Thanks for the quick reply. I'll see what I can do in the meantime to get some form of iscsi working.

**Comment by travisghansen** [comment]
There is no upgrade path between the 2 projects but it would be pretty easy to run this: https://github.com/travisghansen/freenas-iscsi-provisioner

I’m not currently building arm images but an alternative is to simply run the provisioner out of the cluster (including potentially on FreeNAS itself). Arm images probably wouldn’t be too hard to build for that project but non-csi drivers are essentially dead.

**Comment by travisghansen** [comment]
Oh wow! Can you share your yaml file (remove secrets obviously)? There are others that have been interested in running with arm and I can point them to this temporarily.

Thanks!

**Comment by PBXForums** [comment]
Sorry for the delay, I only just noticed this.

This should be enough:
[Archive.zip](https://github.com/democratic-csi/charts/files/4795534/Archive.zip)

**Comment by travisghansen** [comment]
Thanks! I’ll take a look.

**Comment by travisghansen** [comment]
Can you share your experiences so far after using it on arm for a bit?

**Comment by travisghansen** [comment]
I've released a new version of the chart which fixes many things and allows for setting the images via `values.yaml`. Should make this easier.
