### ISSUE TITLE
one deployment with iSCSI and NFS

### ISSUE THREAD

**Issue by UMB8998** [democratic-csi/charts#6]
Hello Again, it's been working with iSCSI perfectly but I need to add some NFS storage for ReadWriteMany will it be possible to have it on the same deployment or I need to make a new one?

**Comment by travisghansen** [comment]
You need a separate deployment. There should be an example for nfs and generally it’s far less moving parts so should be easier to get going than iscsi.

**Comment by UMB8998** [comment]
OK, thank you very much
