### ISSUE TITLE
Create a second StorageClass

### ISSUE THREAD

**Issue by mpkayeuk** [democratic-csi/charts#7]
I successfully installed this into my cluster using Helm, and it works great!  Thank you.

I would now like to create a second StorageClass which points to a different FreeNAS pool on the same server.  Can you give some pointers on how to achieve that?

**Comment by travisghansen** [comment]
Sure! You really only need to ensure a few things:

- Use a new helm release name for each deployment
- Make sure you have a unique `csiDriver.name` in the values file
- Use unqiue names for your storage classes (per cluster)
- Use a unique parent dataset (ie: don't try to use the same parent across deployments or clusters)

For example I run the following:

```
helm upgrade \
--install \
--values freenas-iscsi.yaml \
--namespace democratic-csi \
zfs-iscsi democratic-csi/democratic-csi

helm upgrade \
--install \
--values freenas-nfs.yaml \
--namespace democratic-csi \
zfs-nfs democratic-csi/democratic-csi
```

Where the respective `values` files have unique `csiDriver.name` (which is essentially arbitrary).

Also note, I intend in the future to create a sort of *meta* (or *aggregate*) driver which will use the `instance_id` setting in the config so I'd set those now to completely globally unique values as well (I use a guid generator for mine). The purpose of the meta driver is to allow for multiple configurations to service a single storage class (so you could eventually add a new pool to an existing appliance OR you could add a 2nd, 3rd, etc appliance to keep scaling out without the need to create new storage classes).

**Comment by mpkayeuk** [comment]
Fantastic.  That worked perfectly!  Really appreciate the quick response, I'm a total novice with K8S (my cluster is 3 days old), but this stuff and your FreeNAS CSI Driver is brilliant.  Thanks Travis.

**Comment by travisghansen** [comment]
Wow, csi (particularly one without any documentation...which is why I've never advertised this project) is a pretty steep hill to climb for your first cluster :)

If you don't mind sharing a little info it would help me:

- How did you find out about this project anyhow?
- What k8s 'distro' are you using?
- Are you running with nfs/iscsi or both?
- What FreeNAS version are you running?

**Comment by mpkayeuk** [comment]
> If you don't mind sharing a little info it would help me:

Sure, of course.

> * How did you find out about this project anyhow?

I was looking for some way to automatically provision storage for my pods.  Google got me from that idea to freenas-provisioner and after reading the issues there, I spotted your posts about the CSI rewrite.

> * What k8s 'distro' are you using?

No distro.  I built my cluster using kubeadm and applying config using kubectl. Installed on CentOS 7 VM images built with Packer and Ansible.  Master and worker nodes were provisioned using Terraform.

> * Are you running with nfs/iscsi or both?

So far NFS only.

> * What FreeNAS version are you running?

FreeNAS-11.3-U1

**Comment by travisghansen** [comment]
Perfect thanks! I'd read over this from a node prep standpoint just to make sure you have your bases covered: https://netapp-trident.readthedocs.io/en/stable-v20.04/kubernetes/operations/tasks/worker.html

At some point I'll also implement an 'ephemeral' driver in this project as well that provisions node-local storage using zfs datasets as well. Saving that for the next round of updates...

**Comment by mpkayeuk** [comment]
Funny you should mention the node prep!  I did stumble on that.  I already had the NFS tools installed, I was mounting manually provisioned NFS shares that way (actually 1 share with subfolder sharing enabled).  But I still had to go an create those sub folders on FreeNAS, set permissions, then create the volume definitions in my deployment.  What a pain.

After I first installed this CSI, it didn't work.  I hadn't considered it's dual purpose and it needs the iscsi initiator.  I figured that out pretty quickly from the logs, recreated my Packer/Vsphere images/Terraformed them and joined the new nodes.  Then it all worked perfectly!

**Comment by travisghansen** [comment]
It failed to work even though you weren't using the iscsi 'driver'? That seems odd. Remember what the failure was?

**Comment by mpkayeuk** [comment]
I don't recall I'm afraid.  But it should be reproducible if your node doesn't have the iscsi initiator installed and you run the basic Helm install.

**Comment by travisghansen** [comment]
Hmm I wonder if that’s due to missing dirs or something is all..

**Comment by mpkayeuk** [comment]
Yeah, I'm guessing it's this:

`        - name: iscsi-dir
          mountPath: /etc/iscsi
          mountPropagation: Bidirectional
        - name: iscsi-info
          mountPath: /var/lib/iscsi
          mountPropagation: Bidirectional`

**Comment by travisghansen** [comment]
Yeah I’ll need to clean that up in the charts I guess..

**Comment by travisghansen** [comment]
Working on massive improvements to the chart. Not sure if I'm going to remove the `iscsi` requirements just yet, but all other issues have been dealt with.
